Fix Fernet.encrypt() to actually return bytes.
oz123/python-fernet pull request #1
Opened 2016-09-15 17:05 UTC by SethMichaelLarson

Previously was returning None, without this change this library is broken. Consider incrementing version and release to PyPI.

2016-09-15 19:29 UTC, oz123 commented on fernet.py
> -    """
Why did you remove the link ?

2016-09-15 19:30 UTC, oz123 commented on fernet.py
> -    def encrypt(self, data) -> bytes:
I am kind of enthusiastic about type hints, any reason, why they should go away?

2016-09-15 19:30 UTC, oz123 requested changes

2016-09-15 20:03 UTC, SethMichaelLarson commented on fernet.py
> -    def encrypt(self, data) -> bytes:
Not compatible with Python <3.5 and this library supports 3.4.

2016-09-15 20:03 UTC, SethMichaelLarson commented on fernet.py
> -    """
Sorry, I've been running a local copy lately and I removed the link. I'll put it back.

2016-09-15 20:06 UTC, SethMichaelLarson commented
@oz123 Made the two changes you requested, can you re-review? Thanks!

2016-09-16 11:27 UTC, oz123 approved these changes

2016-09-16 11:27 UTC, merged

2016-09-16 11:28 UTC, oz123 commented
Thank you! Yes, I will do the release to pypi and version bump this weekend

2016-09-18 15:03 UTC, oz123 commented
@SethMichaelLarson you can now find the new version in PyPI, thanks for your contribution.